### 第二十一章 PageRank算法

In [26]:
import numpy as np 


def PageRank(R0:np.ndarray, M: np.ndarray, max_iter:int=100, error:float=1e-15) -> np.ndarray:
    """
    PageRank算法
    :param R0 初始向量
    :param M 转移矩阵
    :param max_iter 迭代次数
    :retuan R PageRank向量
    """
    num_iter = 0

    R_sequence = [R0]
    R_old = R0.copy()

    while num_iter < max_iter:
        num_iter += 1
        R_new = M @ R_old
        R_sequence.append(R_new.copy())
        if np.max(np.abs(R_new-R_old)) < error:
            print(f"在第{num_iter}步收敛，结束训练")
            break
        R_old = R_new.copy()
    return R_new.T

M = np.array([[0, 1/2, 1, 0],
              [1/3, 0, 0, 1/2],
              [1/3, 0, 0, 1/2],
              [1/3, 1/2, 0, 0]])
R0 = np.array([[1/4, 1/4, 1/4, 1/4]]).T
print(PageRank(R0, M))
R0 = np.array([[1/3, 1/3, 1/3, 0]]).T
print(PageRank(R0, M))
R0 = np.array([[1, 0, 0, 0]]).T
print(PageRank(R0, M))

在第48步收敛，结束训练
[[0.33333333 0.22222222 0.22222222 0.22222222]]
在第56步收敛，结束训练
[[0.33333333 0.22222222 0.22222222 0.22222222]]
在第51步收敛，结束训练
[[0.33333333 0.22222222 0.22222222 0.22222222]]
